name: Deploy Production
on:
  push:
    branches:
      - production

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: ðŸš€ Build & Deploy Staging Site
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“š Checkout
        uses: actions/checkout@v2
      - name: ðŸŸ¢ Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org
      - name: Install Dependencies & Build
        run: npm install; CI="" npm run build
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
          REACT_APP_ENV: production
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRACING_MOBILITY }}"
          channelId: live
          projectId: tracing-mobility
          target: prod